version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql



  backend:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://fastapi_user:fastapi_pass@mysql_db/fastapi_db"
      SECRET_KEY: "supersecretkey"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  mysql_data:
